name: Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  coverage:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install coverage pytest pytest-cov
        pip install torch
    - name: Run tests with coverage
      run: |
        coverage run -m pytest
    - name: Report coverage
      run: |
        coverage report
        coverage xml
    - name: Upload coverage artifact
      uses: actions/upload-artifact@v2
      with:
        name: coverage-report
        path: coverage.xml
    - name: Comment coverage on PR
      if: github.event_name == 'pull_request'
      uses: marocchino/sticky-pull-request-comment@v2
      with:
        path: coverage.xml

